import os
from typing import Dict, Any
from mkdocs.config import config_options
from mkdocs.plugins import BasePlugin
from mkdocs.structure.pages import Page
from .utils.git_utils import get_latest_commit_timestamp

CSS_INJECTION = """<style>
.md-content .admonition:first-of-type {
    display: none;
}
</style>"""

JS_INJECTION = """<script>
(() => {
    let banner = document.querySelector(".md-content .admonition:first-of-type");
    let child = banner.children[1];
    let time_updated = new Date(child.innerText * 1000);
    let time_current = new Date();
    let diff_month = (time_current - time_updated) / 1000 / 60 / 60 / 24 / 12;
    if (diff_month > %f) {
        banner.style.display = "flow-root";
        child.innerHTML = "本页面最后更新于 " + Math.round(diff_month) + " 个月前，内容可能已经过时。";
    }
})();
</script>"""

def remove_prefix(text, prefix):
    # for older versions of Python
    if text.startswith(prefix):
        return text[len(prefix):]
    return text

class OutdateWarningPlugin(BasePlugin):
    config_scheme = (
        ("enabled", config_options.Type(bool, default=True)),
        ("month", config_options.Type(int, default=15)),
        ("exclude", config_options.Type(list, default=[])),
        ("exclude_todo", config_options.Type(bool, default=True)),
    )

    exclude_list = []

    def __init__(self) -> None:
        super().__init__()
        self._generate_exclude()

    def _generate_exclude(self) -> None:
        # iterate through each folder
        # for each folder, check if it has a subfolder
        # if it does, exclude its index.md

        # the code is generated by Copilot, say: Thanks Copilot!
        for root, dirs, files in os.walk("./"):
            if "index.md" in files:
                if len(dirs) > 0:
                    self.exclude_list.append(remove_prefix(os.path.join(root, "index.md"), "./docs/"))

    def on_config(self, config: config_options.Config, **kwargs) -> Dict[str, Any]:
        if not self.config.get("enabled"):
            return config
        return config

    def on_page_markdown(self, markdown: str, page: Page, config: config_options.Config, files, **kwargs) -> str:
        if not self.config.get("enabled"):
            return markdown

        for file in self.exclude_list + self.config.get("exclude"):
            if page.file.src_uri == file:
                return markdown
        
        if self.config.get("exclude_todo"):
            if "#TODO" in markdown:
                return markdown
            
        file_path = page.file.abs_src_path
        page_timestamp = get_latest_commit_timestamp(file_path)
        diff_month = int(self.config.get("month"))

        markdown = "!!! warning\n    %s\n\n\n%s\n%s%s" % (page_timestamp, markdown, CSS_INJECTION, JS_INJECTION % diff_month)

        return markdown